# Generated by Django 3.1.2 on 2021-02-01 12:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cjob',
            fields=[
                ('userid', models.CharField(max_length=120)),
                ('j_id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('skills_req', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('c_id', models.IntegerField(primary_key='true', serialize=False, verbose_name='')),
                ('C_title', models.CharField(blank='false', max_length=50)),
                ('C_desp', models.CharField(blank='false', max_length=50)),
                ('plat', models.CharField(blank='false', max_length=200)),
                ('link', models.CharField(blank='false', max_length=500)),
                ('skill', models.CharField(blank='false', max_length=50)),
                ('rating', models.FloatField(blank='false')),
                ('price', models.IntegerField(blank='false')),
            ],
        ),
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('status', models.BooleanField(null='TRUE')),
            ],
        ),
        migrations.CreateModel(
            name='help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=40)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='helps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=40)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='japp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_id', models.CharField(max_length=200)),
                ('usename', models.CharField(max_length=100)),
                ('uemail', models.EmailField(max_length=254)),
                ('sts', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='logindb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank='FALSE', max_length=50)),
                ('firstname', models.CharField(blank='FALSE', max_length=50)),
                ('lastname', models.CharField(blank='TRUE', max_length=50)),
                ('email', models.CharField(blank='FALSE', max_length=256)),
                ('password', models.CharField(blank='FALSE', max_length=50)),
                ('role', models.CharField(blank='FALSE', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='usercu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(blank='false', max_length=50)),
                ('c_id', models.IntegerField(blank='False')),
                ('sts', models.CharField(blank='false', max_length=50)),
                ('token', models.CharField(blank='false', max_length=50, unique='true')),
            ],
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dob', models.DateField(blank='FALSE')),
                ('uname', models.CharField(blank='False', max_length=50, unique='true')),
                ('cname', models.CharField(blank='False', max_length=50)),
                ('Department', models.CharField(blank='False', max_length=50)),
                ('sem', models.IntegerField(blank='False')),
                ('yroj', models.IntegerField(blank='False')),
                ('skilllist', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8), size=8)),
                ('aoilist', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8)),
            ],
        ),
    ]
