# Generated by Django 3.1.2 on 2021-02-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='japp',
            name='token',
            field=models.CharField(blank='false', max_length=50, unique='true'),
        ),
    ]
