# Generated by Django 3.1.2 on 2021-02-01 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0002_japp_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='helps',
        ),
    ]
