# Generated by Django 3.1.2 on 2021-02-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0003_delete_helps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='japp',
            name='j_id',
            field=models.IntegerField(max_length=200),
        ),
    ]
